# Generated by Django 3.0.3 on 2020-07-21 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_auto_20200720_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cargo',
            field=models.ForeignKey(default='Sin Cargo', on_delete=django.db.models.deletion.SET_DEFAULT, to='registro.Cargo'),
        ),
    ]
