# Generated by Django 3.0.3 on 2020-07-21 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_auto_20200720_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.Cargo'),
        ),
    ]
