# Generated by Django 3.0.3 on 2020-07-21 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_auto_20200720_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='rut',
            field=models.ForeignKey(default='11.111.111-K', on_delete=django.db.models.deletion.CASCADE, to='registro.Persona'),
        ),
    ]
