# Generated by Django 3.0.3 on 2020-07-21 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_auto_20200720_2313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cargo',
            new_name='Tipo_persona',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='cargo',
            new_name='tipo',
        ),
        migrations.RenameField(
            model_name='tipo_persona',
            old_name='nombre_cargo',
            new_name='tipo',
        ),
    ]
